import canonicalLaneMathlib.AdmissibleClass

namespace HautevilleHouse
namespace MartingalesDiscreteParameterTheoremCanonicalLaneLean

/-!
# Martingale Representation Theorem Package

For discrete-parameter martingales with respect to a filtration generated by
independent increments, every square-integrable martingale can be represented
as a discrete stochastic integral.
-/

structure MartingaleRepresentationPackage {Ω : Type} [inst : MeasurableSpace Ω]
    {F : Filtration} {X_adapted : AdaptedProcess Ω F} {X : Martingale Ω F X_adapted} where
  squareIntegrable : ∀ n, Integrable (λ ω => (X_adapted.process n ω)^2)
  representationExists : ∃ (H : Nat → Ω → ℝ) (ε : AdaptedProcess Ω F),
    (∀ n, Measurable (H n)) ∧ (∀ n, H n is adapted) ∧
    (∀ n, X_adapted.process n = ∑_{k=0}^{n-1} H k * (ε.process (k+1) - ε.process k))

structure MartingaleRepresentationEvidence {Ω : Type} [inst : MeasurableSpace Ω]
    {F : Filtration} {X_adapted : AdaptedProcess Ω F} {X : Martingale Ω F X_adapted}
    (P : MartingaleRepresentationPackage Ω F X_adapted X) where
  squareIntegrableClosed : P.squareIntegrable
  representationExistsClosed : P.representationExists

def MartingaleRepresentationClosed {Ω : Type} [inst : MeasurableSpace Ω]
    {F : Filtration} {X_adapted : AdaptedProcess Ω F} {X : Martingale Ω F X_adapted}
    (P : MartingaleRepresentationPackage Ω F X_adapted X) : Prop :=
  P.squareIntegrable ∧ P.representationExists

theorem martingale_representation_closed_from_evidence
    {Ω : Type} [inst : MeasurableSpace Ω] {F : Filtration}
    {X_adapted : AdaptedProcess Ω F} {X : Martingale Ω F X_adapted}
    (P : MartingaleRepresentationPackage Ω F X_adapted X) (E : MartingaleRepresentationEvidence P) :
    MartingaleRepresentationClosed P := by
  exact And.intro E.squareIntegrableClosed E.representationExistsClosed

end MartingalesDiscreteParameterTheoremCanonicalLaneLean
end HautevilleHouse